In [1]:
import pandas as pd
import numpy as np
d=[1,2,3,4]
data=pd.Series(d)
print(type(data))

<class 'pandas.core.series.Series'>

In [2]:
print(d)

[1, 2, 3, 4]

In [4]:
import pandas as pd
d = [1,2,3,4]
data = pd.Series(d)
print(data)

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
print(type(data))

<class 'pandas.core.series.Series'>

In [7]:
data = {
    'name':['tharun','karthik','sagar'],
    'age':[22,25,21],
    'salary':[30000,15000,40000]
}
d = pd.DataFrame(data)
print(d)

      name  age  salary
0   tharun   22   30000
1  karthik   25   15000
2    sagar   21   40000

In [8]:
print(d.head(2))

      name  age  salary
0   tharun   22   30000
1  karthik   25   15000

In [9]:
print(d.tail(1))

    name  age  salary
2  sagar   21   40000

In [12]:
print(d.describe())

             age        salary
count   3.000000      3.000000
mean   22.666667  28333.333333
std     2.081666  12583.057392
min    21.000000  15000.000000
25%    21.500000  22500.000000
50%    22.000000  30000.000000
75%    23.500000  35000.000000
max    25.000000  40000.000000

In [13]:
print(d.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

In [14]:
print(d.index)

RangeIndex(start=0, stop=3, step=1)

In [15]:
print(d.columns)

Index(['name', 'age', 'salary'], dtype='object')

In [16]:
d.iloc[0]

name      tharun
age           22
salary     30000
Name: 0, dtype: object

In [17]:
d.loc[1]

name      karthik
age            25
salary      15000
Name: 1, dtype: object

In [18]:
d.memory_usage()

Index     132
name       24
age        24
salary     24
dtype: int64

In [19]:
d.shape

(3, 3)

In [20]:
d.dtypes

name      object
age        int64
salary     int64
dtype: object

In [21]:
d.isnull().sum()

name      0
age       0
salary    0
dtype: int64

In [22]:
df=pd.read_csv('df.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'df.csv'

In [23]:
df = pd.read_csv("dataclean.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'dataclean.csv'

In [25]:
df = pd.read_csv("C:\Users\tharu\OneDrive\Desktop\sqlproject\dataclean.csv")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (ipython-input-315418629.py, line 1)

In [26]:
from google.colab import files
import pandas as pd

# Upload the file
uploaded = files.upload()

# After uploading, read it using pandas
df = pd.read_csv("dataclean.csv")
print(df.head())

Saving dataclean.csv to dataclean.csv
   Sale_ID Customer_Name Region Product_Name  Quantity  Unit_Price  \
0       31       Pooja T  North        Chair         2    21542.02
1      173       Pooja M  South   Smartphone         8    30240.21
2       85       Priya R   West       Tablet         9     4678.18
3      200       Rahul M   West      Monitor         5    23223.66
4       61       Anita S  NORTH     Keyboard         1    20054.00

   Total_Amount  Unnamed: 7 Payment_Method Delivery_Status
0      44526.02         NaN            UPI        Canceled
1     195127.77         NaN         Online         Pending
2      33727.96         NaN            NaN       delivered
3     124878.89         NaN           Cahs      Delivereed
4      21408.64         NaN            NaN         Pending

In [27]:
df

,Sale_ID,Customer_Name,Region,Product_Name,Quantity,Unit_Price,Total_Amount,Unnamed: 7,Payment_Method,Delivery_Status
0,31,Pooja T,North,Chair,2,21542.02,44526.02,NaN,UPI,Canceled
1,173,Pooja M,South,Smartphone,8,30240.21,195127.77,NaN,Online,Pending
2,85,Priya R,West,Tablet,9,4678.18,33727.96,NaN,NaN,delivered
3,200,Rahul M,West,Monitor,5,23223.66,124878.89,NaN,Cahs,Delivereed
4,61,Anita S,NORTH,Keyboard,1,20054.00,21408.64,NaN,NaN,Pending
...,...,...,...,...,...,...,...,...,...,...
205,107,Ravi S,EAST,Printer,7,8132.92,57640.16,NaN,NaN,NaN
206,15,Rahul P,West,Tablet,6,38363.03,233803.86,NaN,Cash,delivered
207,93,Manish T,North,Keyboard,2,16411.34,30502.43,NaN,Online,NaN
208,180,Ravi P,West,Smartwatch,6,43244.79,212536.45,NaN,UPI,Delivered
209,103,Priya M,South,Mouse,8,1752.03,12021.20,NaN,Cash,Delivereed

In [29]:
df.to_string()

'     Sale_ID Customer_Name Region Product_Name  Quantity  Unit_Price  Total_Amount  Unnamed: 7 Payment_Method Delivery_Status\n0         31       Pooja T  North        Chair         2    21542.02      44526.02         NaN            UPI        Canceled\n1        173       Pooja M  South   Smartphone         8    30240.21     195127.77         NaN         Online         Pending\n2         85       Priya R   West       Tablet         9     4678.18      33727.96         NaN            NaN       delivered\n3        200       Rahul M   West      Monitor         5    23223.66     124878.89         NaN           Cahs      Delivereed\n4         61       Anita S  NORTH     Keyboard         1    20054.00      21408.64         NaN            NaN         Pending\n5        156     Sneha P    South        Mouse         3     2917.96       9480.88         NaN         Online       delivered\n6         46        Amit K  NORTH        Chair         4    13481.40      58429.15         NaN         Online             NaN\n7        183       Sneha K  South      Printer         5    16018.30      83379.15         NaN           Card         PENDING\n8         10       Anita P    NaN      Monitor         8     8000.71      54779.40         NaN         Online        Canceled\n9        197       Anita P   west       Tablet         5    31106.99     130240.51         NaN         Online       delivered\n10       137       Priya S   EAST   Smartphone         5    29130.90     163553.77         NaN         Online       delivered\n11       188     Anita K    North       Tablet         8    26369.52     245851.90         NaN            UPI             NaN\n12       171       Divya T  North   Smartphone         1    13540.27      15354.47         NaN            NaN       delivered\n13       127       Anita T   EAST       Laptop         3    14003.01      35737.23         NaN         Online       Delivered\n14        16       Sneha M  North   Smartphone         6    44057.37     299413.77         NaN           Card       Delivered\n15        74       Rahul T  North        Mouse         4     5195.04      22609.43         NaN         Online             NaN\n16       166       Rahul M  NORTH       Tablet         4    40261.70     137752.90         NaN           Cash         PENDING\n17        19       Anita P   west      Monitor         6    22466.90     135749.10         NaN           Card         Pending\n18       169        Amit S   West      Monitor         2    19370.72      31429.96         NaN            NaN         PENDING\n19        94        Ravi P    NaN      Monitor         1    10191.54       9628.07         NaN            NaN      Delivereed\n20        76       Anita S   EAST     Keyboard         9    27015.17     235891.43         NaN            UPI        Canceled\n21        56       Kiran P    NaN     Keyboard         5    37837.06     214904.12         NaN         Online      Delivereed\n22       148       Sneha K  NORTH   Smartphone         4    22348.15      85832.98         NaN           Cahs             NaN\n23       110        Amit R  South     Keyboard         6    49394.93     272559.75         NaN            NaN        Canceled\n24       109       Kiran R    NaN   Smartwatch         8    13511.01      86876.76         NaN            UPI         PENDING\n25       143       Rahul P    NaN        Mouse         5     3225.45      15451.60         NaN           Cash       Delivered\n26        26       Anita R  NORTH     Keyboard         8    11473.62      88155.60         NaN           Card      Delivereed\n27       126       Kiran R   west       Tablet         2    33391.82      54115.59         NaN            UPI             NaN\n28        17       Anita T  South   Smartphone         8    40985.14     390569.96         NaN           Card         Pending\n29       174       Kiran S  NORTH       Laptop        10    18287.99     188049.09         NaN            NaN         PENDING\n30       193       Divya T   East        Chair         2     4221.66       8099.37         NaN         Online      Delivereed\n31        70       Sneha K  NORTH     Keyboard         2    22242.65      42033.06         NaN            NaN         Pending\n32       102       Divya P  NORTH      Monitor         3    25271.10      61773.27         NaN         Online        Canceled\n33        68      Manish M   West   Smartphone        10    34840.11     366133.66         NaN            NaN             NaN\n34       105       Divya T  North        Chair         2    12503.74      26852.03         NaN           Card         PENDING\n35       133       Priya S  NORTH      Printer         5    19340.75      83267.30         NaN           Cash       Delivered\n36       181       Sneha M  NORTH     Keyboard         7    17612.79     107844.67         NaN            UPI             NaN\n37        96       Pooja R   East   Smartwatch         9     1670.05      14477.27         NaN           Cash      Delivereed\n38        83        Amit M   West        Mouse         7    23075.21     157825.64         NaN           Cahs        Canceled\n39       160       Priya S  NORTH      Printer         3    33835.70     114863.77         NaN           Cash         PENDING\n40       198       Kiran R   EAST        Chair         1    41436.58      33619.54         NaN            NaN             NaN\n41       163        Ravi P   EAST        Chair         3    30265.08      78238.36         NaN            NaN             NaN\n42       151       Priya R    NaN     Keyboard        10    38233.98     374525.58         NaN            NaN         PENDING\n43        97       Priya P   East     Keyboard         5    25934.73     117921.32         NaN           Cahs         Pending\n44        96       Pooja R   East   Smartwatch         9     1670.05      14477.27         NaN           Cash      Delivereed\n45        69       Rahul P  South        Chair         1    18012.98      17496.93         NaN           Cash       delivered\n46       157       Pooja R   EAST      Printer         5    19983.41     110886.53         NaN           Cash             NaN\n47        87       Anita S   West      Monitor         2    27683.56      58636.76         NaN           Card       Delivered\n48       101       Anita P   West        Chair         7    12444.56      96713.20         NaN            UPI         PENDING\n49        39       Kiran T  North      Printer        10    28073.73     272852.70         NaN            UPI        Canceled\n50        25       Anita K    NaN        Mouse         2     3478.83       8347.20         NaN           Cash             NaN\n51       184     Divya S      NaN       Laptop         6    31127.72     181905.95         NaN           Cash         PENDING\n52       118       Divya S   west        Chair         7    41298.45     340002.59         NaN            NaN         Pending\n53        30       Priya R  South        Chair         2    34085.42      60950.29         NaN         Online         Pending\n54        20       Priya S  North        Chair         9    12275.62      98116.36         NaN            NaN         PENDING\n55       136       Rahul T   west      Printer         2    29318.01      51898.48         NaN           Card             NaN\n56       140       Anita M  NORTH     Keyboard         6     8713.05      48339.39         NaN         Online       delivered\n57        67       Pooja P  South       Tablet         5     6296.84      25510.75         NaN         Online         PENDING\n58        66       Divya P  South        Chair         4    23786.67      85869.64         NaN           Card       delivered\n59         6       Pooja S   West   Smartphone         1    33401.90      37050.30         NaN           Card             NaN\n60       147      Manish S  South      Monitor         1    48343.78      41998.62         NaN           Cahs             NaN\n61        57       Anita S    NaN   Smartphone         5    12490.19      58350.36         NaN           Cash         Pending\n62        98       Divya T   East      Monitor         4    46171.54     185294.95         NaN           Cash        Canceled\n63       129        Amit S    NaN       Laptop         1    49930.75      56867.10         NaN            NaN       Delivered\n64        80        Ravi K   west       Tablet         8     6026.79      38808.00         NaN           Cahs      Delivereed\n65       116       Rahul R   west     Keyboard         5    37581.41     175784.43         NaN           Cahs       Delivered\n66       175       Priya T   EAST   Smartphone         9    27660.02     277460.00         NaN         Online       Delivered\n67        32       Anita P   EAST   Headphones         5    20393.51     108970.28         NaN           Cahs        Canceled\n68        13       Rahul T  North   Smartphone         9    37793.01     376681.25         NaN           Cash        Canceled\n69        36       Priya P   East   Smartwatch         5    30636.66     166517.12         NaN            NaN         PENDING\n70        29       Sneha K  North        Chair         8    25639.67     234056.95         NaN           Cash       delivered\n71        43       Divya S   west   Headphones         4     2159.56       7577.91         NaN            UPI             NaN\n72       116       Rahul R   west     Keyboard         5    37581.41     175784.43         NaN           Cahs       Delivered\n73        99      Manish S   west       Laptop         5    36576.50     207569.88         NaN            NaN      Delivereed\n74       144       Anita S   West       Tablet         5    15182.91      64375.06         NaN            NaN      Delivereed\n75        52        Ravi R    NaN        Chair         2    23315.39      53833.13         NaN           Card         PENDING\n76       119     Divya K     EAST        Chair         4    32734.97     138031.79         NaN            NaN        Canceled\n77       171       Divya T  North   Smartphone         1    13540.27      15354.47         NaN            NaN       delivered\n78        77       Divya S   west   Smartwatch         4     6912.14      24248.72         NaN            NaN       delivered\n79        42       Anita S   East   Smartphone         7    43736.17     350066.98         NaN           Card             NaN\n80       159       Priya T   East      Printer         5    48417.13     261305.31         NaN           Card       delivered\n81        79       Priya R   west   Headphones         6     9792.64      47337.19         NaN           Card        Canceled\n82       125        Amit R   West   Headphones         6    38944.06     260642.66         NaN           Cash        Canceled\n83        27        Ravi M   west     Keyboard         5    21727.37     128509.47         NaN            NaN         PENDING\n84       141       Priya K   East       Tablet        10     3438.36      28628.91         NaN            NaN      Delivereed\n85       179        Ravi R  North      Printer         5    26253.80     156951.66         NaN           Cahs        Canceled\n86       123       Sneha K   EAST        Mouse         6     3966.95      21667.94         NaN           Cahs       Delivered\n87         3        Amit M   West     Keyboard        10    14631.34     167926.83         NaN            NaN      Delivereed\n88        78       Kiran R   West     Keyboard         5    36504.67     217320.11         NaN         Online        Canceled\n89        47        Amit P   West      Printer         7     4428.72      33037.66         NaN         Online        Canceled\n90       128       Priya M    NaN      Printer         9    30089.63     265607.77         NaN         Online       Delivered\n91       113       Divya S   West        Chair         6    11731.22      61663.01         NaN            NaN             NaN\n92        91       Kiran M    NaN   Smartwatch         3    49850.33     145715.60         NaN           Cash      Delivereed\n93        86       Divya S  North   Headphones         5    35640.84     192673.49         NaN           Cash         PENDING\n94       142       Divya T    NaN      Monitor         5    11562.88      58099.92         NaN           Cahs       Delivered\n95        37     Rahul T      NaN   Smartwatch         1     5522.62       5353.80         NaN           Cash       Delivered\n96       120      Manish K   East       Laptop         1    15913.86      15866.91         NaN           Card       delivered\n97        62       Divya R  North      Monitor        10    28655.21     232348.14         NaN           Card             NaN\n98        23       Sneha M  NORTH     Keyboard         1    33994.86      40578.51         NaN           Cash      Delivereed\n99       139       Kiran R  NORTH   Smartphone         3    37307.48     133044.90         NaN            NaN       delivered\n100      112       Rahul K  NORTH   Smartwatch         1    28730.52      30865.77         NaN         Online         PENDING\n101       34       Kiran S  South   Headphones         6    14964.38      87566.21         NaN            NaN        Canceled\n102       12        Ravi K   East       Tablet         7    30224.04     201816.45         NaN           Cahs       delivered\n103      129        Amit S    NaN       Laptop         1    49930.75      56867.10         NaN            NaN       Delivered\n104      168       Kiran M  South   Headphones         8    44346.86     415863.13         NaN           Cash      Delivereed\n105        7       Priya M   west     Keyboard         6     8970.05      50704.55         NaN            NaN         PENDING\n106       28       Divya R   West   Smartwatch         4    48466.76     200007.22         NaN           Cash         PENDING\n107      172        Amit M  South   Smartwatch         4    15756.41      51624.29         NaN            NaN             NaN\n108       16       Sneha M  North   Smartphone         6    44057.37     299413.77         NaN           Card       Delivered\n109      145       Kiran R  NORTH        Mouse         4    25512.85     115659.11         NaN           Cash      Delivereed\n110        5       Rahul K    NaN        Mouse         2    48682.67      92634.72         NaN            UPI             NaN\n111       33       Priya K    NaN        Chair        10    49808.73     413065.93         NaN         Online        Canceled\n112      114       Kiran P  South       Laptop         5    39641.91     161212.91         NaN            NaN         Pending\n113      153        Ravi S  South   Smartwatch         8    23143.78     152333.47         NaN           Cash         PENDING\n114      121       Kiran M    NaN      Printer         9    21537.21     212618.97         NaN           Cahs         PENDING\n115      195        Amit P   East       Tablet         7    25640.33     205917.30         NaN         Online         Pending\n116      115       Priya S   EAST      Monitor         3    10838.94      36243.41         NaN         Online       delivered\n117       11       Pooja M  NORTH      Printer         4    49868.96     170618.21         NaN           Cash             NaN\n118       63       Divya R  North   Smartwatch         7    17040.28     117120.54         NaN           Cahs        Canceled\n119      149       Rahul P   EAST   Headphones         6    39176.78     195230.06         NaN         Online       delivered\n120      154       Priya T  NORTH     Keyboard        10    28161.50     314487.11         NaN           Cahs             NaN\n121      177       Priya T   EAST       Tablet         1    18262.65      17083.23         NaN            NaN      Delivereed\n122        1       Priya K   west   Headphones         4     7837.36      26364.82         NaN           Cash       delivered\n123      190       Kiran K    NaN       Tablet         8    49865.86     448475.71         NaN            NaN        Canceled\n124      185      Manish S   East       Laptop         3    42584.80     136855.05         NaN           Cash         Pending\n125       71      Manish R   west        Chair         9    38957.43     345690.53         NaN            UPI        Canceled\n126      164       Pooja R    NaN       Laptop         7    18850.67     143544.83         NaN         Online        Canceled\n127       65       Priya P  North       Laptop         4    10768.67      34810.89         NaN           Card         Pending\n128       45       Rahul R   west       Laptop         2    30231.99      56731.83         NaN           Cahs       delivered\n129      138        Amit K   west       Laptop         3    14390.25      47702.12         NaN            UPI       Delivered\n130       41       Kiran R   East       Tablet         7     2214.53      16968.57         NaN           Cahs             NaN\n131      124     Anita P    North       Laptop         6    12934.88      65996.57         NaN           Card       Delivered\n132       24       Sneha K   West   Headphones         4    27278.00      93407.83         NaN            UPI      Delivereed\n133      159       Priya T   East      Printer         5    48417.13     261305.31         NaN           Card       delivered\n134      155       Pooja P   West      Printer        10    24305.82     209113.77         NaN           Cahs       Delivered\n135       82     Priya T    North       Tablet         3    40745.96     144197.95         NaN           Card       Delivered\n136       40        Ravi S   West   Headphones         2    18330.25      37538.64         NaN         Online         PENDING\n137      178       Divya P   East       Tablet         2    36086.21      84978.84         NaN            UPI         Pending\n138       48       Priya P   west        Mouse         5    33677.75     156681.21         NaN         Online         Pending\n139       95        Ravi R   west        Mouse         3    46455.97     135918.06         NaN           Cash       Delivered\n140      162       Anita R   East   Smartphone         5    42376.99     178080.04         NaN            NaN       delivered\n141       44       Priya S   EAST        Mouse         7    34296.39     273076.47         NaN           Cash       Delivered\n142      146        Ravi M  North     Keyboard         2    43243.39      89107.65         NaN           Cahs         PENDING\n143        4       Sneha S   East   Headphones         6     6008.30      34318.36         NaN            UPI       delivered\n144      106       Priya M  South   Smartphone         8     9151.87      67342.13         NaN           Cash        Canceled\n145       54       Kiran P    NaN       Laptop         9    13210.72     135462.87         NaN           Card             NaN\n146      134       Priya K  NORTH   Smartphone         6    40776.69     250176.81         NaN         Online       delivered\n147      191       Priya T   west   Smartwatch         3    35878.65     126034.14         NaN            UPI       delivered\n148      165       Divya R   West   Smartwatch         8    45294.74     318007.66         NaN           Cahs      Delivereed\n149      196       Rahul R   East      Printer         4    17955.13      84486.90         NaN           Cash        Canceled\n150       50       Anita M   EAST     Keyboard         8    22665.83     160561.21         NaN            NaN         Pending\n151       81     Divya S     East       Laptop         5    47112.12     233462.15         NaN           Cahs      Delivereed\n152       35       Pooja P  North        Mouse         5    46656.05     196290.07         NaN            UPI       Delivered\n153        8       Priya T   East        Mouse         4     9006.72      34289.74         NaN           Card         PENDING\n154      111       Divya S   West      Monitor         8     6226.01      47444.47         NaN         Online        Canceled\n155       92       Sneha M   EAST      Printer         2    43028.92      80199.15         NaN            UPI         PENDING\n156       84       Pooja T  North        Chair         2    

In [30]:
print(df.to_string())

     Sale_ID Customer_Name Region Product_Name  Quantity  Unit_Price  Total_Amount  Unnamed: 7 Payment_Method Delivery_Status
0         31       Pooja T  North        Chair         2    21542.02      44526.02         NaN            UPI        Canceled
1        173       Pooja M  South   Smartphone         8    30240.21     195127.77         NaN         Online         Pending
2         85       Priya R   West       Tablet         9     4678.18      33727.96         NaN            NaN       delivered
3        200       Rahul M   West      Monitor         5    23223.66     124878.89         NaN           Cahs      Delivereed
4         61       Anita S  NORTH     Keyboard         1    20054.00      21408.64         NaN            NaN         Pending
5        156     Sneha P    South        Mouse         3     2917.96       9480.88         NaN         Online       delivered
6         46        Amit K  NORTH        Chair         4    13481.40      58429.15         NaN         Online             NaN
7        183       Sneha K  South      Printer         5    16018.30      83379.15         NaN           Card         PENDING
8         10       Anita P    NaN      Monitor         8     8000.71      54779.40         NaN         Online        Canceled
9        197       Anita P   west       Tablet         5    31106.99     130240.51         NaN         Online       delivered
10       137       Priya S   EAST   Smartphone         5    29130.90     163553.77         NaN         Online       delivered
11       188     Anita K    North       Tablet         8    26369.52     245851.90         NaN            UPI             NaN
12       171       Divya T  North   Smartphone         1    13540.27      15354.47         NaN            NaN       delivered
13       127       Anita T   EAST       Laptop         3    14003.01      35737.23         NaN         Online       Delivered
14        16       Sneha M  North   Smartphone         6    44057.37     299413.77         NaN           Card       Delivered
15        74       Rahul T  North        Mouse         4     5195.04      22609.43         NaN         Online             NaN
16       166       Rahul M  NORTH       Tablet         4    40261.70     137752.90         NaN           Cash         PENDING
17        19       Anita P   west      Monitor         6    22466.90     135749.10         NaN           Card         Pending
18       169        Amit S   West      Monitor         2    19370.72      31429.96         NaN            NaN         PENDING
19        94        Ravi P    NaN      Monitor         1    10191.54       9628.07         NaN            NaN      Delivereed
20        76       Anita S   EAST     Keyboard         9    27015.17     235891.43         NaN            UPI        Canceled
21        56       Kiran P    NaN     Keyboard         5    37837.06     214904.12         NaN         Online      Delivereed
22       148       Sneha K  NORTH   Smartphone         4    22348.15      85832.98         NaN           Cahs             NaN
23       110        Amit R  South     Keyboard         6    49394.93     272559.75         NaN            NaN        Canceled
24       109       Kiran R    NaN   Smartwatch         8    13511.01      86876.76         NaN            UPI         PENDING
25       143       Rahul P    NaN        Mouse         5     3225.45      15451.60         NaN           Cash       Delivered
26        26       Anita R  NORTH     Keyboard         8    11473.62      88155.60         NaN           Card      Delivereed
27       126       Kiran R   west       Tablet         2    33391.82      54115.59         NaN            UPI             NaN
28        17       Anita T  South   Smartphone         8    40985.14     390569.96         NaN           Card         Pending
29       174       Kiran S  NORTH       Laptop        10    18287.99     188049.09         NaN            NaN         PENDING
30       193       Divya T   East        Chair         2     4221.66       8099.37         NaN         Online      Delivereed
31        70       Sneha K  NORTH     Keyboard         2    22242.65      42033.06         NaN            NaN         Pending
32       102       Divya P  NORTH      Monitor         3    25271.10      61773.27         NaN         Online        Canceled
33        68      Manish M   West   Smartphone        10    34840.11     366133.66         NaN            NaN             NaN
34       105       Divya T  North        Chair         2    12503.74      26852.03         NaN           Card         PENDING
35       133       Priya S  NORTH      Printer         5    19340.75      83267.30         NaN           Cash       Delivered
36       181       Sneha M  NORTH     Keyboard         7    17612.79     107844.67         NaN            UPI             NaN
37        96       Pooja R   East   Smartwatch         9     1670.05      14477.27         NaN           Cash      Delivereed
38        83        Amit M   West        Mouse         7    23075.21     157825.64         NaN           Cahs        Canceled
39       160       Priya S  NORTH      Printer         3    33835.70     114863.77         NaN           Cash         PENDING
40       198       Kiran R   EAST        Chair         1    41436.58      33619.54         NaN            NaN             NaN
41       163        Ravi P   EAST        Chair         3    30265.08      78238.36         NaN            NaN             NaN
42       151       Priya R    NaN     Keyboard        10    38233.98     374525.58         NaN            NaN         PENDING
43        97       Priya P   East     Keyboard         5    25934.73     117921.32         NaN           Cahs         Pending
44        96       Pooja R   East   Smartwatch         9     1670.05      14477.27         NaN           Cash      Delivereed
45        69       Rahul P  South        Chair         1    18012.98      17496.93         NaN           Cash       delivered
46       157       Pooja R   EAST      Printer         5    19983.41     110886.53         NaN           Cash             NaN
47        87       Anita S   West      Monitor         2    27683.56      58636.76         NaN           Card       Delivered
48       101       Anita P   West        Chair         7    12444.56      96713.20         NaN            UPI         PENDING
49        39       Kiran T  North      Printer        10    28073.73     272852.70         NaN            UPI        Canceled
50        25       Anita K    NaN        Mouse         2     3478.83       8347.20         NaN           Cash             NaN
51       184     Divya S      NaN       Laptop         6    31127.72     181905.95         NaN           Cash         PENDING
52       118       Divya S   west        Chair         7    41298.45     340002.59         NaN            NaN         Pending
53        30       Priya R  South        Chair         2    34085.42      60950.29         NaN         Online         Pending
54        20       Priya S  North        Chair         9    12275.62      98116.36         NaN            NaN         PENDING
55       136       Rahul T   west      Printer         2    29318.01      51898.48         NaN           Card             NaN
56       140       Anita M  NORTH     Keyboard         6     8713.05      48339.39         NaN         Online       delivered
57        67       Pooja P  South       Tablet         5     6296.84      25510.75         NaN         Online         PENDING
58        66       Divya P  South        Chair         4    23786.67      85869.64         NaN           Card       delivered
59         6       Pooja S   West   Smartphone         1    33401.90      37050.30         NaN           Card             NaN
60       147      Manish S  South      Monitor         1    48343.78      41998.62         NaN           Cahs             NaN
61        57       Anita S    NaN   Smartphone         5    12490.19      58350.36         NaN           Cash         Pending
62        98       Divya T   East      Monitor         4    46171.54     185294.95         NaN           Cash        Canceled
63       129        Amit S    NaN       Laptop         1    49930.75      56867.10         NaN            NaN       Delivered
64        80        Ravi K   west       Tablet         8     6026.79      38808.00         NaN           Cahs      Delivereed
65       116       Rahul R   west     Keyboard         5    37581.41     175784.43         NaN           Cahs       Delivered
66       175       Priya T   EAST   Smartphone         9    27660.02     277460.00         NaN         Online       Delivered
67        32       Anita P   EAST   Headphones         5    20393.51     108970.28         NaN           Cahs        Canceled
68        13       Rahul T  North   Smartphone         9    37793.01     376681.25         NaN           Cash        Canceled
69        36       Priya P   East   Smartwatch         5    30636.66     166517.12         NaN            NaN         PENDING
70        29       Sneha K  North        Chair         8    25639.67     234056.95         NaN           Cash       delivered
71        43       Divya S   west   Headphones         4     2159.56       7577.91         NaN            UPI             NaN
72       116       Rahul R   west     Keyboard         5    37581.41     175784.43         NaN           Cahs       Delivered
73        99      Manish S   west       Laptop         5    36576.50     207569.88         NaN            NaN      Delivereed
74       144       Anita S   West       Tablet         5    15182.91      64375.06         NaN            NaN      Delivereed
75        52        Ravi R    NaN        Chair         2    23315.39      53833.13         NaN           Card         PENDING
76       119     Divya K     EAST        Chair         4    32734.97     138031.79         NaN            NaN        Canceled
77       171       Divya T  North   Smartphone         1    13540.27      15354.47         NaN            NaN       delivered
78        77       Divya S   west   Smartwatch         4     6912.14      24248.72         NaN            NaN       delivered
79        42       Anita S   East   Smartphone         7    43736.17     350066.98         NaN           Card             NaN
80       159       Priya T   East      Printer         5    48417.13     261305.31         NaN           Card       delivered
81        79       Priya R   west   Headphones         6     9792.64      47337.19         NaN           Card        Canceled
82       125        Amit R   West   Headphones         6    38944.06     260642.66         NaN           Cash        Canceled
83        27        Ravi M   west     Keyboard         5    21727.37     128509.47         NaN            NaN         PENDING
84       141       Priya K   East       Tablet        10     3438.36      28628.91         NaN            NaN      Delivereed
85       179        Ravi R  North      Printer         5    26253.80     156951.66         NaN           Cahs        Canceled
86       123       Sneha K   EAST        Mouse         6     3966.95      21667.94         NaN           Cahs       Delivered
87         3        Amit M   West     Keyboard        10    14631.34     167926.83         NaN            NaN      Delivereed
88        78       Kiran R   West     Keyboard         5    36504.67     217320.11         NaN         Online        Canceled
89        47        Amit P   West      Printer         7     4428.72      33037.66         NaN         Online        Canceled
90       128       Priya M    NaN      Printer         9    30089.63     265607.77         NaN         Online       Delivered
91       113       Divya S   West        Chair         6    11731.22      61663.01         NaN            NaN             NaN
92        91       Kiran M    NaN   Smartwatch         3    49850.33     145715.60         NaN           Cash      Delivereed
93        86       Divya S  North   Headphones         5    35640.84     192673.49         NaN           Cash         PENDING
94       142       Divya T    NaN      Monitor         5    11562.88      58099.92         NaN           Cahs       Delivered
95        37     Rahul T      NaN   Smartwatch         1     5522.62       5353.80         NaN           Cash       Delivered
96       120      Manish K   East       Laptop         1    15913.86      15866.91         NaN           Card       delivered
97        62       Divya R  North      Monitor        10    28655.21     232348.14         NaN           Card             NaN
98        23       Sneha M  NORTH     Keyboard         1    33994.86      40578.51         NaN           Cash      Delivereed
99       139       Kiran R  NORTH   Smartphone         3    37307.48     133044.90         NaN            NaN       delivered
100      112       Rahul K  NORTH   Smartwatch         1    28730.52      30865.77         NaN         Online         PENDING
101       34       Kiran S  South   Headphones         6    14964.38      87566.21         NaN            NaN        Canceled
102       12        Ravi K   East       Tablet         7    30224.04     201816.45         NaN           Cahs       delivered
103      129        Amit S    NaN       Laptop         1    49930.75      56867.10         NaN            NaN       Delivered
104      168       Kiran M  South   Headphones         8    44346.86     415863.13         NaN           Cash      Delivereed
105        7       Priya M   west     Keyboard         6     8970.05      50704.55         NaN            NaN         PENDING
106       28       Divya R   West   Smartwatch         4    48466.76     200007.22         NaN           Cash         PENDING
107      172        Amit M  South   Smartwatch         4    15756.41      51624.29         NaN            NaN             NaN
108       16       Sneha M  North   Smartphone         6    44057.37     299413.77         NaN           Card       Delivered
109      145       Kiran R  NORTH        Mouse         4    25512.85     115659.11         NaN           Cash      Delivereed
110        5       Rahul K    NaN        Mouse         2    48682.67      92634.72         NaN            UPI             NaN
111       33       Priya K    NaN        Chair        10    49808.73     413065.93         NaN         Online        Canceled
112      114       Kiran P  South       Laptop         5    39641.91     161212.91         NaN            NaN         Pending
113      153        Ravi S  South   Smartwatch         8    23143.78     152333.47         NaN           Cash         PENDING
114      121       Kiran M    NaN      Printer         9    21537.21     212618.97         NaN           Cahs         PENDING
115      195        Amit P   East       Tablet         7    25640.33     205917.30         NaN         Online         Pending
116      115       Priya S   EAST      Monitor         3    10838.94      36243.41         NaN         Online       delivered
117       11       Pooja M  NORTH      Printer         4    49868.96     170618.21         NaN           Cash             NaN
118       63       Divya R  North   Smartwatch         7    17040.28     117120.54         NaN           Cahs        Canceled
119      149       Rahul P   EAST   Headphones         6    39176.78     195230.06         NaN         Online       delivered
120      154       Priya T  NORTH     Keyboard        10    28161.50     314487.11         NaN           Cahs             NaN
121      177       Priya T   EAST       Tablet         1    18262.65      17083.23         NaN            NaN      Delivereed
122        1       Priya K   west   Headphones         4     7837.36      26364.82         NaN           Cash       delivered
123      190       Kiran K    NaN       Tablet         8    49865.86     448475.71         NaN            NaN        Canceled
124      185      Manish S   East       Laptop         3    42584.80     136855.05         NaN           Cash         Pending
125       71      Manish R   west        Chair         9    38957.43     345690.53         NaN            UPI        Canceled
126      164       Pooja R    NaN       Laptop         7    18850.67     143544.83         NaN         Online        Canceled
127       65       Priya P  North       Laptop         4    10768.67      34810.89         NaN           Card         Pending
128       45       Rahul R   west       Laptop         2    30231.99      56731.83         NaN           Cahs       delivered
129      138        Amit K   west       Laptop         3    14390.25      47702.12         NaN            UPI       Delivered
130       41       Kiran R   East       Tablet         7     2214.53      16968.57         NaN           Cahs             NaN
131      124     Anita P    North       Laptop         6    12934.88      65996.57         NaN           Card       Delivered
132       24       Sneha K   West   Headphones         4    27278.00      93407.83         NaN            UPI      Delivereed
133      159       Priya T   East      Printer         5    48417.13     261305.31         NaN           Card       delivered
134      155       Pooja P   West      Printer        10    24305.82     209113.77         NaN           Cahs       Delivered
135       82     Priya T    North       Tablet         3    40745.96     144197.95         NaN           Card       Delivered
136       40        Ravi S   West   Headphones         2    18330.25      37538.64         NaN         Online         PENDING
137      178       Divya P   East       Tablet         2    36086.21      84978.84         NaN            UPI         Pending
138       48       Priya P   west        Mouse         5    33677.75     156681.21         NaN         Online         Pending
139       95        Ravi R   west        Mouse         3    46455.97     135918.06         NaN           Cash       Delivered
140      162       Anita R   East   Smartphone         5    42376.99     178080.04         NaN            NaN       delivered
141       44       Priya S   EAST        Mouse         7    34296.39     273076.47         NaN           Cash       Delivered
142      146        Ravi M  North     Keyboard         2    43243.39      89107.65         NaN           Cahs         PENDING
143        4       Sneha S   East   Headphones         6     6008.30      34318.36         NaN            UPI       delivered
144      106       Priya M  South   Smartphone         8     9151.87      67342.13         NaN           Cash        Canceled
145       54       Kiran P    NaN       Laptop         9    13210.72     135462.87         NaN           Card             NaN
146      134       Priya K  NORTH   Smartphone         6    40776.69     250176.81         NaN         Online       delivered
147      191       Priya T   west   Smartwatch         3    35878.65     126034.14         NaN            UPI       delivered
148      165       Divya R   West   Smartwatch         8    45294.74     318007.66         NaN           Cahs      Delivereed
149      196       Rahul R   East      Printer         4    17955.13      84486.90         NaN           Cash        Canceled
150       50       Anita M   EAST     Keyboard         8    22665.83     160561.21         NaN            NaN         Pending
151       81     Divya S     East       Laptop         5    47112.12     233462.15         NaN           Cahs      Delivereed
152       35       Pooja P  North        Mouse         5    46656.05     196290.07         NaN            UPI       Delivered
153        8       Priya T   East        Mouse         4     9006.72      34289.74         NaN           Card         PENDING
154      111       Divya S   West      Monitor         8     6226.01      47444.47         NaN         Online        Canceled
155       92       Sneha M   EAST      Printer         2    43028.92      80199.15         NaN            UPI         PENDING
156       84       Pooja T  North        Chair         2    47431.92      83775.70         NaN            UPI         PENDING

In [32]:
df.isnull().sum()

Sale_ID              0
Customer_Name        0
Region              30
Product_Name         0
Quantity             0
Unit_Price           0
Total_Amount         0
Unnamed: 7         210
Payment_Method      44
Delivery_Status     31
dtype: int64

In [37]:
df['Region'].unique()

array(['North', 'South', 'West', nan, 'East'], dtype=object)

In [34]:
df['Region']=df['Region'].replace('NORTH','North')
df['Region']=df['Region'].replace('EAST','East')
df['Region']=df['Region'].replace('west','West')

In [36]:
df['Region']=df['Region'].replace('nan','South')

In [41]:
df['Region'].unique()

array(['North', 'South', 'West', nan, 'East'], dtype=object)

In [43]:
df['Region'].fillna('South',inplace=True)

/tmp/ipython-input-2092082367.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Region'].fillna('South',inplace=True)

In [42]:
df['Region'].unique()

array(['North', 'South', 'West', nan, 'East'], dtype=object)

In [44]:
df['Region'].fillna('South', inplace=True)

In [45]:
df['Region'].unique()

array(['North', 'South', 'West', 'East'], dtype=object)

In [46]:
df

,Sale_ID,Customer_Name,Region,Product_Name,Quantity,Unit_Price,Total_Amount,Unnamed: 7,Payment_Method,Delivery_Status
0,31,Pooja T,North,Chair,2,21542.02,44526.02,NaN,UPI,Canceled
1,173,Pooja M,South,Smartphone,8,30240.21,195127.77,NaN,Online,Pending
2,85,Priya R,West,Tablet,9,4678.18,33727.96,NaN,NaN,delivered
3,200,Rahul M,West,Monitor,5,23223.66,124878.89,NaN,Cahs,Delivereed
4,61,Anita S,North,Keyboard,1,20054.00,21408.64,NaN,NaN,Pending
...,...,...,...,...,...,...,...,...,...,...
205,107,Ravi S,East,Printer,7,8132.92,57640.16,NaN,NaN,NaN
206,15,Rahul P,West,Tablet,6,38363.03,233803.86,NaN,Cash,delivered
207,93,Manish T,North,Keyboard,2,16411.34,30502.43,NaN,Online,NaN
208,180,Ravi P,West,Smartwatch,6,43244.79,212536.45,NaN,UPI,Delivered
209,103,Priya M,South,Mouse,8,1752.03,12021.20,NaN,Cash,Delivereed

In [47]:
df = df.drop('Unnamed: 7',axis = 1)

In [48]:
df

,Sale_ID,Customer_Name,Region,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Delivery_Status
0,31,Pooja T,North,Chair,2,21542.02,44526.02,UPI,Canceled
1,173,Pooja M,South,Smartphone,8,30240.21,195127.77,Online,Pending
2,85,Priya R,West,Tablet,9,4678.18,33727.96,NaN,delivered
3,200,Rahul M,West,Monitor,5,23223.66,124878.89,Cahs,Delivereed
4,61,Anita S,North,Keyboard,1,20054.00,21408.64,NaN,Pending
...,...,...,...,...,...,...,...,...,...
205,107,Ravi S,East,Printer,7,8132.92,57640.16,NaN,NaN
206,15,Rahul P,West,Tablet,6,38363.03,233803.86,Cash,delivered
207,93,Manish T,North,Keyboard,2,16411.34,30502.43,Online,NaN
208,180,Ravi P,West,Smartwatch,6,43244.79,212536.45,UPI,Delivered
209,103,Priya M,South,Mouse,8,1752.03,12021.20,Cash,Delivereed

In [49]:
df['Payment_Method']= df['Payment_Method'].ffill()

In [50]:
df

,Sale_ID,Customer_Name,Region,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Delivery_Status
0,31,Pooja T,North,Chair,2,21542.02,44526.02,UPI,Canceled
1,173,Pooja M,South,Smartphone,8,30240.21,195127.77,Online,Pending
2,85,Priya R,West,Tablet,9,4678.18,33727.96,Online,delivered
3,200,Rahul M,West,Monitor,5,23223.66,124878.89,Cahs,Delivereed
4,61,Anita S,North,Keyboard,1,20054.00,21408.64,Cahs,Pending
...,...,...,...,...,...,...,...,...,...
205,107,Ravi S,East,Printer,7,8132.92,57640.16,UPI,NaN
206,15,Rahul P,West,Tablet,6,38363.03,233803.86,Cash,delivered
207,93,Manish T,North,Keyboard,2,16411.34,30502.43,Online,NaN
208,180,Ravi P,West,Smartwatch,6,43244.79,212536.45,UPI,Delivered
209,103,Priya M,South,Mouse,8,1752.03,12021.20,Cash,Delivereed

In [51]:
df['Delivery_Status'] = df['Delivery_Status'].bfill()

In [52]:
df

,Sale_ID,Customer_Name,Region,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Delivery_Status
0,31,Pooja T,North,Chair,2,21542.02,44526.02,UPI,Canceled
1,173,Pooja M,South,Smartphone,8,30240.21,195127.77,Online,Pending
2,85,Priya R,West,Tablet,9,4678.18,33727.96,Online,delivered
3,200,Rahul M,West,Monitor,5,23223.66,124878.89,Cahs,Delivereed
4,61,Anita S,North,Keyboard,1,20054.00,21408.64,Cahs,Pending
...,...,...,...,...,...,...,...,...,...
205,107,Ravi S,East,Printer,7,8132.92,57640.16,UPI,delivered
206,15,Rahul P,West,Tablet,6,38363.03,233803.86,Cash,delivered
207,93,Manish T,North,Keyboard,2,16411.34,30502.43,Online,Delivered
208,180,Ravi P,West,Smartwatch,6,43244.79,212536.45,UPI,Delivered
209,103,Priya M,South,Mouse,8,1752.03,12021.20,Cash,Delivereed

In [53]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
205    False
206    False
207    False
208    False
209    False
Length: 210, dtype: bool

In [54]:
df.duplicated().sum()

np.int64(7)

In [55]:
df=df.drop_duplicates()

In [56]:
df.duplicated().sum()

np.int64(0)

In [57]:
df

,Sale_ID,Customer_Name,Region,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Delivery_Status
0,31,Pooja T,North,Chair,2,21542.02,44526.02,UPI,Canceled
1,173,Pooja M,South,Smartphone,8,30240.21,195127.77,Online,Pending
2,85,Priya R,West,Tablet,9,4678.18,33727.96,Online,delivered
3,200,Rahul M,West,Monitor,5,23223.66,124878.89,Cahs,Delivereed
4,61,Anita S,North,Keyboard,1,20054.00,21408.64,Cahs,Pending
...,...,...,...,...,...,...,...,...,...
205,107,Ravi S,East,Printer,7,8132.92,57640.16,UPI,delivered
206,15,Rahul P,West,Tablet,6,38363.03,233803.86,Cash,delivered
207,93,Manish T,North,Keyboard,2,16411.34,30502.43,Online,Delivered
208,180,Ravi P,West,Smartwatch,6,43244.79,212536.45,UPI,Delivered
209,103,Priya M,South,Mouse,8,1752.03,12021.20,Cash,Delivereed

In [62]:
import numpy as np

cons = [df['Quantity'] >= 8, df['Quantity'] >= 5, df['Quantity'] >= 2]
res = ['A', 'B', 'C']

df['condition'] = np.select(cons, res, default='D')
df

/tmp/ipython-input-3210546806.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['condition'] = np.select(cons, res, default='D')

,Sale_ID,Customer_Name,Region,Product_Name,Quantity,Unit_Price,Total_Amount,Payment_Method,Delivery_Status,condition
0,31,Pooja T,North,Chair,2,21542.02,44526.02,UPI,Canceled,C
1,173,Pooja M,South,Smartphone,8,30240.21,195127.77,Online,Pending,A
2,85,Priya R,West,Tablet,9,4678.18,33727.96,Online,delivered,A
3,200,Rahul M,West,Monitor,5,23223.66,124878.89,Cahs,Delivereed,B
4,61,Anita S,North,Keyboard,1,20054.00,21408.64,Cahs,Pending,D
...,...,...,...,...,...,...,...,...,...,...
205,107,Ravi S,East,Printer,7,8132.92,57640.16,UPI,delivered,B
206,15,Rahul P,West,Tablet,6,38363.03,233803.86,Cash,delivered,B
207,93,Manish T,North,Keyboard,2,16411.34,30502.43,Online,Delivered,C
208,180,Ravi P,West,Smartwatch,6,43244.79,212536.45,UPI,Delivered,B
209,103,Priya M,South,Mouse,8,1752.03,12021.20,Cash,Delivereed,A

In [63]:
print(df.to_csv('mynewdata.csv'))

None